[build-system]
requires = ["whool"]
build-backend = "whool.buildapi"

[project]
name = "odoo-addons-oca-partner-contact"
version = "20.0.20260918.0"
dependencies = [
    "odoo-addon-partner_contact_personal_information_page @ git+https://github.com/OCA/partner-contact.git@refs/pull/2452/head#subdirectory=partner_contact_personal_information_page",
]
