# See LICENSE file for full copyright and licensing details.
{'name': 'Portal Partner Merge',
 'version': '11.0.1.0.0',
 'category': 'Hidden',
 'author': "Camptocamp,Odoo Community Association (OCA)",
 'maintainer': 'Camptocamp',
 'license': 'AGPL-3',
 'website': 'http://www.camptocamp.com/',
 'depends': ['portal', 'base_partner_merge'],
 'data': [],
 'test': [],
 'installable': True,
 'auto_install': False,
 'application': False,
 }
