[project]
name = "odoo-addons-oca-partner-contact"
version = "19.0.20251229.4"
dependencies = [
    "odoo-addon-base_country_state_translatable==19.0.*",
    "odoo-addon-base_location==19.0.*",
    "odoo-addon-base_location_geonames_import==19.0.*",
    "odoo-addon-base_partner_company_group==19.0.*",
    "odoo-addon-base_partner_sequence==19.0.*",
    "odoo-addon-partner_affiliate==19.0.*",
    "odoo-addon-partner_contact_access_link==19.0.*",
    "odoo-addon-partner_contact_address_default==19.0.*",
    "odoo-addon-partner_contact_birthplace==19.0.*",
    "odoo-addon-partner_contact_personal_information_page==19.0.*",
    "odoo-addon-partner_identification==19.0.*",
    "odoo-addon-partner_mobile==19.0.*",
    "odoo-addon-partner_ref_unique==19.0.*",
    "odoo-addon-partner_supplier_ref==19.0.*",
    "odoo-addon-partner_title==19.0.*",
    "odoo-addon-partner_vat_unique==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
